config/routes.rb
Rails.application.routes.draw do

  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  match '/user' => "users#show", :as => :user_root,  via: 'get'

  devise_for :users, :path_prefix => 'd'
  resources :users, :only =>[:show]

  resources :books
  get 'home_page/index'
  root 'home_page#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :admin])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :publisher, :genre)
    end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]

  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author_name %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-large btn-primary'%> 

<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>
</div>
<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<input id="myInput" type="text" placeholder="Search..">

<table class = "table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Publisher</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="myTable">
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.publisher %></td>
        <td><%= book.genre %></td>
        <td><%= link_to 'Show', book %></td>
        <% if current_user %>
          <% if current_user.username == book.user.username %>
            <td><%= link_to 'Edit', edit_book_path(book) %></td>
            <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
        <% if current_user && current_user.admin %>
          <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user && !current_user.admin%>
  <%= link_to 'New Book', new_book_path, :class => 'btn btn-large btn-primary' %>
<% end %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>
|
<%= link_to 'Back', books_path, :class => 'btn btn-large btn-primary' %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<% if current_user && !current_user.admin %>
<%= link_to 'Edit', edit_book_path(@book) %>|
<% end %>
<%= link_to 'Back', books_path %>

app/views/home_page/index.html.erb
<!DOCTYPE html>
<html lang="en">
<body>

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">

      <div class="item active">
        <img src=<%= image_url('la.jpg')%> alt="Los Angeles" style="width:100%;">
        <div class="carousel-caption">
          <h3>Los Angeles</h3>
          <p>LA is always so much fun!</p>
        </div>
      </div>

      <div class="item">
        <img src=<%= image_url('chicago.jpg')%> alt="Chicago" style="width:100%;">
        <div class="carousel-caption">
          <h3>Chicago</h3>
          <p>Thank you, Chicago!</p>
        </div>
      </div>

      <div class="item">
        <img src=<%= image_url('ny.jpg')%> alt="New York" style="width:100%;">
        <div class="carousel-caption">
          <h3>New York</h3>
          <p>We love the Big Apple!</p>
        </div>
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <p class="alert alert-<%= message %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
        <%= value %>

  </p>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
<div class="container-fluid">
  <div class="navbar-header">
    <a class="navbar-brand" href=<%= home_page_index_path %>>Book-Store</a>
  </div>
  <ul class="nav navbar-nav">
    <% if current_user && current_user.admin %>
      <li><a href= <%= users_path %>>View User</a></li>
    <% end %>
    <li><a href=<%= books_path %>>List Books</a></li>
  </ul>
  <% if current_user %>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user.admin %>
        <li><a  title="Logged in as Admin" data-toggle="popover" data-placement="bottom" data-content=<%= current_user.email %> >View Profile</a></li>
      <% else %>
        <li><a  title="Logged in as" data-toggle="popover" data-placement="bottom" data-content=<%= current_user.email %> >View Profile</a></li>
      <% end %>
      <li><span class="glyphicon glyphicon-user"></span> <%= link_to 'Edit', edit_user_registration_path %></li>
      <li><span class="glyphicon glyphicon-user"></span> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
    </ul>
  <% else %>
    <ul class="nav navbar-nav navbar-right">
      <li><span class="glyphicon glyphicon-user"></span> <%= link_to 'Sign in', new_user_session_path %></li>
      <li><span class="glyphicon glyphicon-user"></span> <%= link_to 'Sign up', new_user_registration_path %></li>
    </ul>
  <% end %>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation'%>
  <div class = "container" >
    <% if notice %></p>
      <%= render 'layouts/messages', message: 'success' %>
    <% elsif alert %></p>
      <%= render 'layouts/messages', message: 'danger' %>
    <% end %>
    <%= yield %>
  </div>
  <footer class="container-fluid bg-4 text-center">
    <p>Posted by: Jaison, copyright<i class="fa fa-copyright" style="font-size:15px"></i> Contact information: <a href="mailto:someone@example.com">someone@example.com</a>.</p>
  </footer>
</body>
</html>

app/views/users/index.html.erb
<h2>Listing all the users registered on the website</h2>

<table class = "table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users = User.all %>
    <% @users.each do |user| %>
      <% if !(current_user.username == user.username) %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.email %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<table class = "table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= current_user.username %></td>
      <td><%= current_user.email %></td>
    </tr>
  </tbody>
</table>